### ISSUE TITLE
Whois21 not working

### ISSUE THREAD

**Issue by rezaqomy** [MPCodeWriter21/whois21#10]
@MPCodeWriter21 

when i run whois21 -h i see this error
```
> whois21 -h            
Traceback (most recent call last):
  File "/home/USER/.local/bin/whois21", line 8, in <module>
    sys.exit(run())
             ^^^^^
  File "/home/USER/.local/lib/python3.12/site-packages/whois21/__main__.py", line 179, in run
    main()
  File "/home/USER/.local/lib/python3.12/site-packages/whois21/__main__.py", line 79, in main
    args = parser.parse_args()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1896, in parse_args
    args, argv = self.parse_known_args(args, namespace)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/argparse.py", line 1932, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.local/lib/python3.12/site-packages/log21/Argparse.py", line 1070, in _parse_known_args
    start_index = consume_optional(start_index)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/USER/.local/lib/python3.12/site-packages/log21/Argparse.py", line 944, in consume_optional
    action, option_string, explicit_arg = option_tuple
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: too many values to unpack (expected 3)
```

**Comment by MPCodeWriter21** [comment]
Hi @rezaqomy 👋 
Thank you for your contribution to this repo!
Please mention your exact Python version and your OS.

**Comment by rezaqomy** [comment]
I use Arch btw, and my Python version is 3.12.6. However, I tested it on my Termux, and I encountered the same error.

**Comment by MPCodeWriter21** [comment]
@rezaqomy Thanks for the details! I will look into the issue and update you.
