### ISSUE TITLE
Whois problem with non utf-8 characters.

### ISSUE THREAD

**Issue by ghost** [MPCodeWriter21/whois21#2]
Whois' request for this  IP  gives the following error. I am guessing that the reason for this error is related that the whois record contains French characters (8 rue de la ville l'évêque).

 whois = whois21.WHOIS("62.4.13.111")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Maciek\AppData\Roaming\Python\Python311\site-packages\whois21\__init__.py", line 173, in __init__
    self.whois(domain, servers, timeout, use_rdap, force_rdap)
  File "C:\Users\Maciek\AppData\Roaming\Python\Python311\site-packages\whois21\__init__.py", line 202, in whois
    self.__whois()
  File "C:\Users\Maciek\AppData\Roaming\Python\Python311\site-packages\whois21\__init__.py", line 267, in __whois
    self.__call_whois_servers()
  File "C:\Users\Maciek\AppData\Roaming\Python\Python311\site-packages\whois21\__init__.py", line 425, in __call_whois_servers
    lines = self.__raw.decode('utf-8').split('\n')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe2 in position 882: invalid continuation byte

**Comment by MPCodeWriter21** [comment]
Hello @haps-basset, thank you for your report regarding the issue with the encoding of the whois record.

I have just published a new version of the package (v1.3.0) which has options for customizing the way the whois record is decoded and also tries to detect the encoding automatically. It should fix the issue you reported. Please let me know if you have any other problems with the package.

You can install the new version with pip:
```
pip install whois21==1.3.0
```

Best regards.

**Comment by ghost** [comment]
Many thanks
